### ISSUE TITLE
Prepare flow / complete notebook for workshop

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#102]
This notebook contains the code that (ideally) is produced by the end of the workshop. This serves as an speakers note for  the teacher. It should also contain places to ask questions, or give explanation.
It is probably a good idea to base it on the tutorial-notebook.

**Comment by vincentvanhees** [comment]
Issue moved to [NLeSC/mcfly-tutorial #5](https://github.com/NLeSC/mcfly-tutorial/issues/5) via [**ZenHub**](https://www.zenhub.com/)
