### ISSUE TITLE
dependency on tkinter

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#106]
When tests after ```pip install mcfly``` on a new ubuntu docker image, I get 
'ImportError (No module named _tkinter, please install the python-tk package)'
```apt install python-tk``` solves the issue.
The dependency is only needed for the tutorial because it is a matplotlib dependency.
We could solve this by creating a separate repo for the tutorial. This way the matplotlib dependency can be removed from mcfly altogether.

**Comment by dafnevk** [comment]
In the `find_architecture` module we have a function to plot the training process. If we want to keep that functionality, we also need to keep the matplotlib dependency.

**Comment by dafnevk** [comment]
I removed the plotting function, since we have the javascript visualization for plotting the training process. The matplotlib dependency is thus no longer necessary.
