### ISSUE TITLE
Move wiki to gh pages

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#108]
Gh pages is version controlled and is more easily navigated than github wiki.

**Comment by vincentvanhees** [comment]
possibly the visualisation can be moved to a separate repository

**Comment by dafnevk** [comment]
I copied the content of the wiki pages to the sphinx documentation (3e92713  )
The user documentation is now visible at https://mcfly.readthedocs.io/en/latest/. Do we still want it to be available on gh-pages as well?

The links in the README to the documentation need to be updated.

**Comment by cwmeijer** [comment]
@dafnevk Sounds like this was solved with your last referenced commit, judging from the commit message. Can we close this?

**Comment by dafnevk** [comment]
I moved the wiki information to the (version-controlled) documentation pages on readthedocs, but I didn't move the documentation to gh-pages (because the visualization is still running there). I think it's fine like this, if you agree you can close it.

**Comment by cwmeijer** [comment]
Looks great. closing.
