### ISSUE TITLE
Migrate tutorial to new repository

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#114]
- [x] make new repository with name: `mcfly-tutorial`
- [x] migrate `notebooks` en `tutorial` to new repository
- [x] restructure folder structure:
     - [x] folder names
     - [ ] requirements.txt

**Comment by vincentvanhees** [comment]
Issue moved to [NLeSC/mcfly-tutorial #1](https://github.com/NLeSC/mcfly-tutorial/issues/1) via [**ZenHub**](https://www.zenhub.com/)
