### ISSUE TITLE
Work on powerpoint with introduction

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#115]
Oral explanation in talk or during workshop:
	Explain what deep learning tries to solve
		why should researchers be interested in learning / using deep learning
			they need classification
		what kind / group of research questions fit
		why not use classical statistics (classical vs DL approach)
To avoid creating customized features, if desired & To create novel feature you may not have thought about & To classify complex pattern constructed from simpler patterns (and give cat example)
DL is also partly unexplored terrain and therefore may add novelty to their field
	Explain what mcfly tries to solve
		Ease the hyperparameter and architecture choice
Why would I use it instead of caffe tensor flow
	Specific for time series
It uses tensorflow and keras, and mcfly provides an easy access way to start learning Keras (it has a less steep learning curve)
Up to date with latest trends in 2016 informed by literature
use expertise to make the choices so that the users don’t have to
Explain Logistic regression and/or single node in a neural network?

**Comment by vincentvanhees** [comment]
Issue moved to [NLeSC/mcfly-tutorial #3](https://github.com/NLeSC/mcfly-tutorial/issues/3) via [**ZenHub**](https://www.zenhub.com/)
