### ISSUE TITLE
Surpress verbose output of tensorflow

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#131]
Tensorflow gives very verbose output, it would be nice to surpress this, at least in the travis build/ nose testing, also in the tutorial notebooks.
See https://github.com/tensorflow/tensorflow/issues/8340.

**Comment by ClimbsRocks** [comment]
I just added a code snippet on the other thread that you might find useful
https://github.com/tensorflow/tensorflow/issues/8340
