### ISSUE TITLE
LSTM on one dimensional time series forecasting

### ISSUE THREAD

**Issue by nikusha37** [NLeSC/mcfly#132]
Hello,

I am trying to create LSTM model using mcfly. I get the error about dimensions.
I have one dimensional pandas series and I reshape it to (len(series),1,1). 
I think model requires output variable as binary (0,1). But I have just one time series of financial data.
How can I model in this case using mcfly?

Thank you.

**Comment by dafnevk** [comment]
Mcfly currently only supports time series _classification_. (either binary or multiclass). This means that your output variable should be categorical, with one label per time series. This label needs to be represented as a binary (one-hot) matrix. 

Mcfly cannot be used for prediction real value numbers, such as in forecasting. This is something we consider as a future feature.

**Comment by dafnevk** [comment]
Since it seems that this issue (forecasting) falls out of the intended scope of mcfly, we will close the issue.
