### ISSUE TITLE
Multi-thread parallel execution of random search

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#135]
The hyperparameter search could be done on multiple threads on the cpu.

**Comment by atzeus** [comment]
This is automatic in tensorflow at least. Running mcfly with tensorflow already uses all my 4 cpus. Will check with theano.

**Comment by atzeus** [comment]
Theano also automatically uses all my cpu's albeit a bit less efficient then tensorflow it seems (more time spent in non-parallelized code).

**Comment by cwmeijer** [comment]
According to Atze's comments I'm considering this fixed or no longer relevant.
