### ISSUE TITLE
Support k-fold cross validation

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#139]
- [ ] Think about how exactly hyperparamter search + cross validation works
(Take look at e.g. sklearn)
- [ ] Implement k-fold cross validation

**Comment by vincentvanhees** [comment]
Old explorations by @dafnevk are [in this notebook](https://github.com/NLeSC/mcfly-tutorial/blob/master/notebooks/experiments/experiment_PAMAP2_9fold.ipynb)  within the mcfly-tutorial repository.

**Comment by cwmeijer** [comment]
I don't think this is worth the effort. Cross validation will give you a better estimate of the performance of a resulting model, it however doesn't give you a single best model anymore. Also it will take a lot of time to do this with deep learning and random search. I don't think this is a common use case for mcfly. Reopen if you disagree :-)
