### ISSUE TITLE
Visualize the raw timeseries and the learned features as timeseries 

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#140]

**Comment by egpbos** [comment]
Discussed during Team Project sprint 1. Ideas:
- Visualize Fourier frequencies as well.
- Something like this perhaps: https://github.com/yosinski/deep-visualization-toolbox

**Comment by florian-huber** [comment]
Breixo was actually recently working on very nice visualization of what the models learn. But that would be quite far fetched to adapt to mcfly. Overall I believe this issue wasn't picked up, so it seems outdated. I'll close it for now.
