### ISSUE TITLE
Regression 

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#142]
Now we only provide classification, we could also provide regression (numerical target)

**Comment by strcat32** [comment]
Any update on this? Can you use mcfly for regression problems?

**Comment by cwmeijer** [comment]
We don't have plans to implement regression in the near future. Regression would be a very nice addition to current functionality. However, we have chosen to restrict our scope to classification for now so we can focus on polishing the user experience for this type of problem.
If our priorities change, we'll update this issue.
