### ISSUE TITLE
Data loading functionality

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#15]

**Comment by vincentvanhees** [comment]
So far I have focussed on how loading data and getting it in a standardized format. Requiring one type of input format seems difficult, so i have explored to what extend we can handle the lack of standardisation in input format after the data is loaded.

**Comment by dafnevk** [comment]
I propose that for now, we use the code so far to prepare the datasets and save them again in an uniform format.

The rest of our functionality should then require this specific format.
In this way, we can start each of our notebooks with just a single line of data loading.

**Comment by dafnevk** [comment]
The numpy arrays: X_train, y_train, X_val, y_val, X_test, y_test
and possibly a mapping from class numbers -> class names.
