### ISSUE TITLE
Automated tests for Windows

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#153]
Setup automated test runner using appveyor.

**Comment by egpbos** [comment]
Added AppVeyor Windows build. Latest build: https://ci.appveyor.com/project/NLeSC/mcfly/build/job/nljicu1b0bj2y60i

**Comment by egpbos** [comment]
Tensorflow only works on Python 3.5 64 bit.

This gives us two options for Windows builds:
1. Only support Python 3.5 64 bit.
2. Remove Tensorflow from the requirements list and make it an optional requirement, defaulting to Theano on Windows.

@cwmeijer, what shall we do?

**Comment by egpbos** [comment]
Python 3.5 64 bit tests indeed run successfully! The others fail, as expected.

Added AppVeyor badge to README.md as well.
