### ISSUE TITLE
h5py dependency not in pypi

### ISSUE THREAD

**Issue by egpbos** [NLeSC/mcfly#155]
In commit https://github.com/NLeSC/mcfly/commit/13f1c163cecad371cb3badea0b2b657d5b044bde the requirements.txt file was updated to include h5py. This is necessary to save models in the tutorial (https://github.com/NLeSC/mcfly-tutorial/blob/master/notebooks/tutorial/tutorial.ipynb). The latest pypi release does not have this updated requirement and does not install h5py, so it fails at cell 18.

**Comment by dafnevk** [comment]
Closing, because this will be fixed when we do a new release.
