### ISSUE TITLE
Can mcfly support one-class classification?

### ISSUE THREAD

**Issue by helpme1** [NLeSC/mcfly#175]
Some time-series datasets are not suitable for multi-class classification due to imbalance of labels. For example, anomaly detection or credit card fraud detection. Is it fraud or not fraud? Lots of "not fraud" labels but very few "fraud" labels. These applications are more suitable for one-class classification (Is it or is it not?). 

Can mcfly support one-class classification? If not, I would like to suggest to the wonderful mcfly team to consider this as one of the features to implement in future.

Thank you.

**Comment by vincentvanhees** [comment]
yes mcfly can handle single class classification.
