### ISSUE TITLE
Add skip/residual connection to model types

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#179]
**Goal:** Skip connections or also known as residual connections have become a popular technique to enhance deep learning models, it would be good if mcfly could have this functionality.

**How it is done in Keras:** A residual connection on a Convolutional layer can be made as described in https://keras.io/getting-started/functional-api-guide/:
```
from keras.layers import Conv2D, Input

# input tensor for a 3-channel 256x256 image
x = Input(shape=(256, 256, 3))
# 3x3 conv with 3 output channels (same as input channels)
y = Conv2D(3, (3, 3), padding='same')(x)
# this returns x + y.
z = keras.layers.add([x, y])
```
This is also what people suggest elsewhere [here](https://stackoverflow.com/questions/42384602/implementing-skip-connections-in-keras) and [here](https://github.com/keras-team/keras/issues/1321). However, this [code](https://github.com/mbinkowski/nntimeseries/blob/e519739a929a2a6511a2012f3cb5eae6a50d139e/nnts/models/CNN.py) that belongs to [Bińkowski 2017](https://arxiv.org/abs/1703.04122) gives the impression that we should use syntax that involves the `append` function: `outs.append(Convultion1D(....))(out[-1])`.

If I stick to the syntax used in the Keras documentation then the time series adaptation would be:
```
# input tensor for a 3-channel 512 time series
x = Input(shape=(512, 3))
# 3x1 conv with 3 output channels (same as input channels)
y = Convolution1D(3, (3), padding='same')(x)
# this returns x + y.
z = keras.layers.add([x, y], name='skipconnection')

```

**Do we know enough now?**
At the moment mcfly uses sequential models, so this means that we need to revise the architecture somewhat. What we need is academic publications exploring different deep learning architectures for time series that recommend a specific architecture using residual connections. Relying on those recommendations is more convincing than to implement some random architectures ourself.

So far, I have not found any articles with open source code that use residual architectures for deep learning on time series as opposed to images.

**Comment by vincentvanhees** [comment]
I have added a notebook to the mcfly-tutorial repository that explores what syntax to use for skip residual/skip connection: [commit](https://github.com/NLeSC/mcfly-tutorial/commit/a72be7b44f6a849c3e427e19bd31972f41886a4f) and [link to notebook](https://github.com/NLeSC/mcfly-tutorial/blob/master/notebooks/experiments/experiment_skipconnections.ipynb).

**Comment by cwmeijer** [comment]
See for example:
https://stackoverflow.com/questions/49337897/how-to-adapt-resnet-to-time-series-data

**Comment by cwmeijer** [comment]
I made a notebook where I think implemented the method from https://arxiv.org/pdf/1611.06455.pdf.

[resnet_experiment.zip](https://github.com/NLeSC/mcfly/files/4231262/resnet_experiment.zip)

I think the code in this notebook can be parameterized and implemented in mcfly. No hyperparameter tuning whatsoever has been done yet so we will have to investigate the performance still.

**Comment by florian-huber** [comment]
Has become part of new release (ResNet type architecture).
