### ISSUE TITLE
Make release 1.0.2

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#181]
- [x] Check  .zenodo.json 
- [x] set version number in mcfly/_version.py
- [x] check that documentation uses the correct version
- [x] Edit Changelog (based on commits in https://github.com/NLeSC/mcfly/compare/v1.0.1...master)
- [x]  test if package can be installed with pip (`pip install .`)
- [x]  create Github release
- [x]  register on pipy
- [ ] Check doi on zenodo and edit this in citation.cff

**Comment by cwmeijer** [comment]
We tried to do a release for 1.0.2. Two things went wrong: the changelog still said 1.1.0 and there was a bug in the json format of the zenodo config file. The broken zenodo config caused zenodo not to give a doi to this release. We could fix this by creating a zenodo release manually (leaving the changelog and .zenodo config in the zips unfixed) or we could do a new release 1.0.3 entirely just to fix this.
