### ISSUE TITLE
data one hot preprocessing

### ISSUE THREAD

**Issue by Isaamarod** [NLeSC/mcfly#188]
Hi, 

I'm trying to launch the tutorial with my own data set. I have a binary classification with int64 as type .
The y_train arrays shape is: 
int64
(9414,)
Whe I transform using np_utils.to_categorica the result is apparently correct: 
y_train_3=np_utils.to_categorical(y_train, num_classes=2)
print(y_train_3.shape)
print(y_train_3)

(9414, 2)
[[ 1.  0.]
 [ 1.  0.]
 [ 0.  1.]
 ..., 
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  0.]]

Then I save like .npy

The following step is to split y_train  in train,test , val and save like y_train_binary.npy ..

However, when I try to train the models this error occur:

ValueError: Error when checking target: expected activation_5 to have shape (6024,) but got array with shape (2,)

When I search the error is suggested converting labels with np_utils.to_categorical.

Any suggestion? Could be the categorical_crossentropy? How could I change in the model?

**Comment by Isaamarod** [comment]
Hello,
I found the problem, num_classes variable it was wrong.

Thanks,
Isabel

**Comment by cwmeijer** [comment]
Sounds like this has been solved.
