### ISSUE TITLE
update call to deprecated div

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#192]
use / operator instead (I think)

WARNING:tensorflow:From /home/christiaan/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version. Instructions for updating: Deprecated i

**Comment by florian-huber** [comment]
I believe this was solved by moving to tensorflow 2.
