### ISSUE TITLE
Build architecture based on Ordonez et al 

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#20]
Extend the functionality from issue #19 to incorporate architectures that are like those presented in the paper of Ordonez et al, 2016.

**Comment by vincentvanhees** [comment]
I was able to understand the code and added extra annotation
Function generate_DeepConvLSTM_model matches the architecture as described by Ordonez, while genetate_CNN_model deviates from Ordonez as it has less dense layers. This may affect comparability of the two models for evaluating the beneficial value of LSTM.
