### ISSUE TITLE
textual changes for the paper

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#208]
address all the issues from the review concerning the text in the paper

**Comment by cwmeijer** [comment]
I replaced 'Keras' a couple of times with 'Keras API in Tensorflow'. It is not the nicest thing to read like this but it seems the most accurate to me. It just wouldn't be accurate to talk about 'Tensorflow models' etc. Someone needs to review it. All changes that I made were in the software description tex file. You can just search for 'Keras' in it.

Also, I changed the citation to Keras into a citation to the Tensorflow whitepaper from 2015 which the Tensorflow website suggests.

**Comment by florian-huber** [comment]
The revised manuscript is ready to go, so I believe this is essentially done right now.
