### ISSUE TITLE
Reorder tests of architectures in seperate test suites

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#222]
Tests of several architectures are now together in 1 big suite with comments seperating tests for one architecture from tests for the next. Instead of comments we should use test suites to seperate them.

**Comment by florian-huber** [comment]
Since we now anyway work on moving models to individual classes, we can split the tests accordingly --> PR #239

**Comment by bsolino** [comment]
Maybe we can do it in two separate steps, so it's easier to review the code.

**Comment by florian-huber** [comment]
Yes, agreed. I moved the new tests into the "old" modelgen test suite to make the PR #239 a bit simpler.
We can move it to individual test files later (``test_model_cnn.py`` etc.).

**Comment by bsolino** [comment]
Currently working on this on branch reorder_tests_222
