### ISSUE TITLE
Update user documentation

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#231]
The [user documentation](https://mcfly.readthedocs.io/en/latest/user_manual.html) and [technical documentation](https://mcfly.readthedocs.io/en/latest/technical_doc.html) are a bit outdated, it doesn't include the newer architectures.

**Comment by florian-huber** [comment]
Should we maybe plan in a mini-sprint somewhere soon to fix some smaller issues?

**Comment by dafnevk** [comment]
To do: 
- [ ] Remove the User manual (and make sure the info there is available in the docstring
- [ ] rename technical documentation to user documentation
- [ ] Fix and reformat the table of contents (it should be shown in the left panel)

**Comment by dafnevk** [comment]
Probably also good to add:
- [ ] Installation
- [ ] Getting started

**Comment by dafnevk** [comment]
I moved some content around, but I made new issues to make larger changes to the content: #246 #247 #248 #249
