### ISSUE TITLE
Let model classes contain the definition of their model name

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#252]
In modelgen.generate_models we have a mapping of 'magic' strings to default classes. 
```
default_models = {'CNN': Model_CNN,
                      'DeepConvLSTM': Model_ConvLSTM,
                      'ResNet': Model_ResNet,
                      'InceptionTime': Model_InceptionTime}
```
It would be cleaner to have the mapping be build from a string that is extracted from the model class. Like so:    
```
default_models = {ModelCNN.name(): Model_CNN,
                      Model_ConvLSTM.name(): Model_ConvLSTM,
                      Model_ResNet.name(): Model_ResNet,
                      Model_InceptionTime.name(): Model_InceptionTime}
```
Or:
```
models = [CNN, Model_ConvLSTM, Model_ResNet, Model_InceptionTime]
default_models = {model.name(): model for model in models}
```

**Comment by dafnevk** [comment]
NB: the DeepConvLSTM is the only model for which the string identifier is different than its class name. I think it would make sense if 'ConvLSTM' also maps to the ConvLSTM model, but do we also still want DeepConvLSTM to be used? If we don't want breaking changes, we need to keep it in there. Also, the model was called DeepConvLSTM to be consistent with the paper where it was introduced (Ordonez et al, 2016). We could also rename the ConvLSTM class back to DeepConvLSTM.

**Comment by bsolino** [comment]
I like both suggestions, and it seems pretty easy to do. Is there a reason this was not included in the current sprint?

**Comment by bsolino** [comment]
Working on branch name_models_252

**Comment by bsolino** [comment]
This is currently (slightly) blocked by PR #259, as it requires to change names in the test files
