### ISSUE TITLE
Array shape of input to Convolutional layers in DeepConvLSTM - Why Conv2D and not Conv1D?

### ISSUE THREAD

**Issue by rmndrs89** [NLeSC/mcfly#271]
Not really an issue, but I have a question regarding the array shapes of the inputs to the convolutional layers for the DeepConvLSTM model (see: [https://github.com/NLeSC/mcfly/blob/master/mcfly/models/deep_conv_lstm.py](url)).

After the `BatchNormalization` layer, the array is reshaped from a 2-dimensional array to a 3-dimesional array. Thereafter, `Convolution2D` layers are applied to the output of the `Reshape` layer.
After the convolutional layers, the arrays are reshaped to a 2-dimensional array (with shape: (`dim_length`, `filters[-1]`*`dim_channels`)), and subsequently the recurrent layers are applied.

My personal approach would have been to apply a `Conv1D` layer, as we are dealing with timeseries data. Why was an extra dimension added to the array, and why was there chosen to use a `Conv2D` layer?

I think the difference is that in the `Conv2D` layer approach, with `kernel_size=(3, 1)` the convolution is applied on individual channels, where with the `Conv1D` approach the output would average across the `dim_channels` (I think at least, after reading: [https://cs231n.github.io/convolutional-networks/](url))

**Comment by dafnevk** [comment]
Thanks for your question, you are right that this approach results in a convolution per channel, instead of over the channels. This was an architectural choice of the original authors of the DeepConvLSTM model ([Ordonez et al, 2016](https://doi.org/10.3390/s16010115)) The [the mcfly paper](https://www.sciencedirect.com/science/article/pii/S2352711019300202?via%3Dihub#sec2) states the following clarification:

> In contrast to the CNN model, the convolutional layers in the DeepConvLSTM model are applied per channel, and connected in the first LSTM layer. Applying convolutions per channel was reported to be suitable for activity recognition tasks based on wearable sensor data where the channels are not necessarily synchronized in time (each channel corresponds to a different body part) 

I hope this helps!

**Comment by rmndrs89** [comment]
Super, yeah, silly question, but thought I'd just ask for confirmation,
