### ISSUE TITLE
Adapt defaults for evaluation metrics

### ISSUE THREAD

**Issue by maltelueken** [NLeSC/mcfly#306]
Currently, the default metric is 'accuracy' which is only appropriate for classification. We should also add a default for regression, i.e., 'mean_squared_error'.

Note that the kNN model only evaluates on accuracy (or mean squared error), the user cannot supply a custom metric here.

**Comment by cwmeijer** [comment]
Disable KNN model comparison if the metric is not MSE or accuracy. (without a warning as not to confuse users about knns they didn't ask for)
