### ISSUE TITLE
explore hyperas for hyperparameter optimization

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#33]
https://github.com/maxpumperla/hyperas

**Comment by dafnevk** [comment]
Hyperas uses hyperopt to take care of training models with different hyperparameters. It's very flexible in how you define your hyperparameter space.
It would take care of a lot of functionality in our modelgen.py script and find_architecture.py script. We would just need to define the models with their parameters, and provide plotting functionality.

It uses [Tree of Parzen Estimaters (TPE)](https://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization.pdf) for hyperparameter search, which has been applied on Deep networks.

**Comment by dafnevk** [comment]
It is (via hyperopt) also possible to do the training for the optimization in parallel, using mongodb.
