### ISSUE TITLE
Try out SMAC

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#36]
see #34

**Comment by dafnevk** [comment]
pysmac is also only compatible with python 2.7.
Same goes for [HPOlib](https://github.com/automl/HPOlib) which provides a common interface to hyperopt, pysmac and [spearmint](https://github.com/HIPS/Spearmint)

**Comment by dafnevk** [comment]
Since SMAC seems a good algorithm (see #34 ) I propose to fork the pysmac repository and try to make it python 3 compatible

**Comment by cwmeijer** [comment]
SMAC implementations are dependent on a JAVA program that should be running in the background. We don't want a JAVA dependency. We would need to port it even though we can't even find the source code right now.
TPE see above. We would need to adopt the whole hyperopt project to be able to use it.
Spearmint is not applicable for us.
