### ISSUE TITLE
Try out existing code on EEG dataset

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#37]
For now, this is random search.
Investigate whether the codes works and how long the runs take for one model.

**Comment by vincentvanhees** [comment]
I tried to run 200 models, it goes well for a while but then prematurely terminates with an error message that the kernel died. I presume this is a jupyter issue?! Results until crash indicate that none of the models performaned beyond what would be expected from a random number generator.

It may be best to first do some more testing with a simpler classification problem, like PAMAP. If we cannot get it to work with those datasets either then there may be something more fundamentally wrong.

My quick impression from EEG deep literature is that others use more or less the same number of layers, nodes and learning rate. Their classification tasks were different then ours complicating comparisons.
