### ISSUE TITLE
Wiki page technical choices 

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#44]
Document what choices we made.
Model types, achitectures, default parameters etc.

**Comment by dafnevk** [comment]
While writing down our choices, I got to the following questions about our models:
* Why don't we use dropout in the CNN?
* Would it make sense to use Pool layers when the input sequence is relatively long
* We now take accuracy as a measure for performance when picking the best model - why exactly? we could give an option here for other metrics?
* We should compare somewhere to random or majority class prediction
