### ISSUE TITLE
Find literature about UCR handwave gestures

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#52]
Are there any published benchmarks?

**Comment by dafnevk** [comment]
The UCR Time Series archive as a whole is less cited than for example the Pamap2 dataset. I coudn't find any references to the UCR repository from papers that use deep learning.
The datasets within the UCR archive are not specified any further, so we don't know anything about the handwave gestures dataset. 
The authors of the UCR archive argue that you should only report results on all datasets in the archive.

I propose that we don't use the UCR handwave gesture dataset as a real benchmark. Instead, we better use datasets that have been referenced in literature before.
Here's some ideas for other future datasets:
* https://www.kaggle.com/c/seizure-prediction - Closed Kaggle competition on EEG data to predict seizures
* https://archive.ics.uci.edu/ml/datasets/OPPORTUNITY+Activity+Recognition - Human activity recognition dataset, referenced in several papers such as Plotz
*  https://archive.ics.uci.edu/ml/datasets/Gas+Sensor+Array+Drift+Dataset+at+Different+Concentrations gas sensor
* https://www.kaggle.com/c/multilabel-bird-species-classification-nips2013/data bird sound identification
