### ISSUE TITLE
Experiment eecology data

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#53]

**Comment by vincentvanhees** [comment]
Plan as discussed in #50

**Comment by cwmeijer** [comment]
Train set of 1065, somewhat smaller test set, let's say 400. The same sets are used for mcfly as for the alternative method (random forest on features). 
For mcfly I had the following settings:
number_of_models = 25
nr_epochs=20
subset_size=1065 (full train set)
