### ISSUE TITLE
Report on first release

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#56]
Make powerpoint presentation about the first release and the results from the experiments.

**Comment by vincentvanhees** [comment]
Christiaan made ppt, we can use this to now as a startingpoint to write a short document

**Comment by vincentvanhees** [comment]
I drafted a 1 page A4 with a list of key mcfly achievements and ideas for future work. The document is on the onedrive [here](https://nlesc-my.sharepoint.com/personal/v_vanhees_esciencecenter_nl/_layouts/15/guestaccess.aspx?guestaccesstoken=I3QAC5eJz3DwSL2HZNjMuVXfV0bkVoayVNaS0%2bkZsOM%3d&docid=1d72af57a59564db08c923ca1450a3628&rev=1).

To create this document I read through the items on the zenhub board and various documents we created earlier this year. The document may not be complete, but together with Christiaan's slides it may be a useful reference point.
