### ISSUE TITLE
blas without dynamic library warning

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#62]
I am getting this warning in my notebook when running our find_architecture.train_models_on_samples function.

WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.

I followed the standard installation steps from .travis, so I am not sure where it goes wrong. Is this a problem? If yes, how can we make sure that mcfly-users have the correct configuration and do not see this warning?

**Comment by vincentvanhees** [comment]
The Travis log shows the same warning, so this is not specific to my work environment.

**Comment by dafnevk** [comment]
If I create a new conda environment, similar to Travis, I also get the warning.
However, if I then install numpy through conda (instead of just via pip) I don't get the warning anymore, I think it automatically configures the BLAS library.
So I'll add this to the travis file.

**Comment by dafnevk** [comment]
Now the 2.7 build broke, but I think it's fixed by also installing scipy through conda.
