### ISSUE TITLE
save functionality

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#63]
save model weights and architecture:
- model.to_json()
- model.save_weights()
  decide whether to save in mcfly as:
- 2 seperate files for weights and architecture
- a folder containing the 2 files
- a zip containing the 2 files (looks nice, but hides technology to the user)

The filename(s) will be user-defined

possibly with load functionality later

**Comment by vincentvanhees** [comment]
I implemented storage functionality to store the model as two seperate files (weights and architecture seperate) in a folder chosen by the user and a model-name chosen by the user. The model name and the folder are the identifiers the load function needs to retrieve the model.
I choose for a custom implementation rather then relying on the Keras function, which I have reported in issue #67.

**Comment by cwmeijer** [comment]
There are no tests yet for this code right?
You could define model and save it and load it again and then do some assertions on the loaded model. This would be good test for both functionalities.
