### ISSUE TITLE
prepare for Kaggle competition participation

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#65]
https://www.kaggle.com/c/melbourne-university-seizure-prediction

Deadline 14 November

**Comment by dafnevk** [comment]
NB: we have  to be careful what we do with the data. It is stated that:

> As indicated in the Competition Rules, the contest data may only be used for the purposes of this Competition. All other uses, including education, academic, research, commercial and non-commercial uses, are prohibited.

This means we cannot used models on this data for our own research, or write in paper about results on this data set.
