### ISSUE TITLE
Model storage functionality based on Keras functions

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#67]
Currently the keras function to save and load models in hdf5 format only works for python2. Possibly related to depency h5py which only works for python2.

To work around this I implemented a custom function that stores model weights in numpy-files and model architecture in a json file. Once the Keras function has become python3 compatible we can revise this.

The code would then look something like:

import h5py
modelh5=models[0]
modelh5.save('/mydir/mymodel.h5')
modelh5_reloaded = load_model('/mydir/mymodel.h5')

**Comment by cwmeijer** [comment]
was solved with PR #150
