### ISSUE TITLE
Test GPU functionality

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#69]
- [x] log on to DAS5 and clone mcfly
- [x] install requirements: "pip3 install -r requirements.txt --user" was the command I used
- [x] open a notebook and run the simple forecasting example using Keras/Theano
- [ ] Activate GPU utilization
- [ ] run mcfly with pamap2

**Comment by dafnevk** [comment]
In order to request a node with GPU on the DAS-5:
```
srun -N 1 -C TitanX --gres=gpu:1  --time=00:15:00 --pty bash
module load cuda80/toolkit
```

Then install tensorflow-gpu:
```
conda create -n mcfly
source activate mcfly
Conda install pip numpy tensorflow  tensorflow-gpu
pip install mcfly
```

Make sure tensorflow is set as default backend in ~/.keras/keras.json.
Now mcfly/Keras will should with GPU automatically.

**Comment by cwmeijer** [comment]
We used GPUs for the workshop last year so this was thoroughly tested then.
