### ISSUE TITLE
Prep data UCR time series classification

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#7]
Prepare small dataset UCR time series classification archive:

http://www.cs.ucr.edu/~eamonn/time_series_data/
The password for the data (link to 350 Mb zip) is: attempttoclassify
http://www.cs.ucr.edu/~eamonn/time_series_data/UCR_TS_Archive_2015.zip

**Comment by xadgi07** [comment]
Thank you very much

**Comment by pcko1** [comment]
finally the password! thanks!

**Comment by abdelouahab1** [comment]
Yes!

**Comment by benprano** [comment]
Thanks for your post

**Comment by mrkcel** [comment]
Thanks for your help.

**Comment by Asifbinsyed** [comment]
the password has been changed I guess. Does anyone have the new password??

**Comment by vincentvanhees** [comment]
Follow the link as they tell you to and read the documentation you find on the new website.

![image](https://user-images.githubusercontent.com/8362333/180606913-356c6e5b-7249-450b-89bb-3145456848b1.png)

Please note that in the NLeSC/mcfly repository we only used that data for testing. We are not in any way linked to affiliated with the creators or hosts of the data. Please contact them if you have questions.
