### ISSUE TITLE
Add documentation about visualization

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#72]
Update README and/or wiki pages to explain:
- how to open the visualization (README)
- How to interpret the visualization (wiki, reference in README)

**Comment by vincentvanhees** [comment]
Thoughts on visualisation:
- Axes labels needed
- File browser limited to json files
- Clarification that 10 bars are the ten models

**Comment by vincentvanhees** [comment]
done - I have updated the README
