### ISSUE TITLE
Json-output of NaN's should be different for visualization

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#82]
If the model losses are NaN for some reason, the visualization can't read the file because it can't handle NaN. Maybe it works when we output them as a string, or replace them with 0, or change the javascript code to handle the NaNs.

**Comment by cwmeijer** [comment]
I haven't seen this issue coming up in a while and I think this was solved long ago. Closing. It can be reopened or a new issue can be created if we encounter something similar.
