### ISSUE TITLE
Model generation gives obscure warning

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#88]
Model generation (at least in the tutorial) gives the warning below.

/home/christiaan/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py:368: UserWarning: The `regularizers` property of layers/models is deprecated. Regularization losses are now managed via the `losses` layer/model property.
  warnings.warn('The `regularizers` property of '

**Comment by dafnevk** [comment]
This was a bug in Keras but is fixed in version 1.2.1, see https://github.com/fchollet/keras/issues/4777
