### ISSUE TITLE
find alternative dataset for tutorial

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly#96]
PAMAP2 dataset may be uncessarily large and is  maybe problematic (only 9 participants, missing data...)

**Comment by florian-huber** [comment]
Thanks to @sonjageorgievska we now have a list of potential alternative datasets to play with:
https://archive.ics.uci.edu/ml/datasets.html?format=&task=&att=&area=&numAtt=&numIns=&type=ts&sort=nameUp&view=list

**Comment by florian-huber** [comment]
I selected a few datasets that are smaller and work for tutorials. I'll soon add an alternative (quick) tutorial. The dataset I use there was processed and uploaded to zenodo: https://zenodo.org/record/3743603
