### ISSUE TITLE
Support python 3.6

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#99]
Right now, installation doesn't work for Python 3.6.

**Comment by dafnevk** [comment]
It seems that there are no problems with 3.6 (maybe the problem aws with previous versions of specific packages?)

**Comment by mkuzak** [comment]
I think there is still problem with 3.6. I tried to do the installation in new conda environment with Python 3.6 and get the following error when installing Keras:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - keras -> python 3.4* -> xz 5.0.5
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by dafnevk** [comment]
Mcfly works with python 3.6, as can be seen in [Travis](https://travis-ci.org/NLeSC/mcfly).
